### ISSUE TITLE
Add back GRUB2 support for ISO builds

### ISSUE THREAD

**Issue by korewaChino** [FyraLabs/katsu#9]

**Comment by madonuko** [comment]
only thing missing is the bin for the bios and uefi part

**Comment by korewaChino** [comment]
Can you add that then?

**Comment by korewaChino** [comment]
https://github.com/livecd-tools/livecd-tools/blob/2e26b096281e6fd4cf0e10e5bcc0cd5871a690cd/imgcreate/live.py#L155-L275

**Comment by korewaChino** [comment]
https://github.com/search?q=repo%3Aweldr%2Florax+xorriso&type=code

**Comment by korewaChino** [comment]
https://wiki.osdev.org/GRUB

**Comment by korewaChino** [comment]
Genuinely stumped why xorriso wouldn't create an image layout we wanted.

This is an example from Lorax

[livemedia-creator.log](https://github.com/FyraLabs/katsu/files/12874638/livemedia-creator.log)

**Comment by korewaChino** [comment]
Update: UEFI boot now works, but BIOS no longer works
